minimumReleaseAgeExclude:
  - vite@8.3.4
  - "@happy-dom/global-registrator@20.14.6"
  - happy-dom@20.14.6
patchedDependencies:
  "@vitest/browser-playwright@5.0.3": patches/@vitest__browser-playwright@5.0.3.patch
  "@vitest/browser@5.0.3": patches/@vitest__browser@5.0.3.patch
  "@vitest/mocker@5.0.3": patches/@vitest__mocker@5.0.3.patch
  playwright-core@1.63.0: patches/playwright-core@1.63.0.patch
